// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package cel.expr.conformance.test;

import "cel/expr/checked.proto";
import "cel/expr/eval.proto";
import "cel/expr/value.proto";

option cc_enable_arenas = true;
option go_package = "cel.dev/expr/conformance/test";
option java_multiple_files = true;
option java_outer_classname = "SimpleProto";
option java_package = "dev.cel.expr.conformance.test";

// The format of a simple test file, expected to be stored in text format.
message SimpleTestFile {
  string name = 1;
  string description = 2;
  repeated SimpleTestSection section = 3;
}

// A collection of related SimpleTests.
message SimpleTestSection {
  string name = 1;
  string description = 2;
  repeated SimpleTest test = 3;
}

// A test which should run the given CEL program through parsing,
// optionally through checking, then evaluation.
message SimpleTest {
  string name = 1;
  string description = 2;
  string expr = 3;
  bool disable_macros = 4;
  bool disable_check = 5;
  bool check_only = 15;
  repeated cel.expr.Decl type_env = 6;
  string container = 13;
  string locale = 14;
  map<string, cel.expr.ExprValue> bindings = 7;

  oneof result_matcher {
    cel.expr.Value value = 8;
    TypedResult typed_result = 16;
    cel.expr.ErrorSet eval_error = 9;
    ErrorSetMatcher any_eval_errors = 10;
    cel.expr.UnknownSet unknown = 11;
    UnknownSetMatcher any_unknowns = 12;
  }
}

// Matches a result along with deduced expression type.
message TypedResult {
  cel.expr.Value result = 1;
  cel.expr.Type deduced_type = 2;
}

// Matches error results from Eval.
message ErrorSetMatcher {
  repeated cel.expr.ErrorSet errors = 1;
}

// Matches unknown results from Eval.
message UnknownSetMatcher {
  repeated cel.expr.UnknownSet unknowns = 1;
}
