[package]
name = "rscel-macro"
version = {workspace = true}
edition = {workspace = true}
description = {workspace = true}
license = {workspace = true}

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.91"


